### ISSUE TITLE
My name is in mistakenly placed in the list and has not been removed.

### ISSUE THREAD

**Issue by captunnmurika** [bastisawesome/twitchbotsnbigots#2]
Hi, my Twitch username is murika_ and I've created this GitHub account to leave a comment, so excuse me if I don't know how this platform works just yet.

I am aware that my name was also added in False-positives.txt, but frankly has not been removed from NamelistMASTER.txt which has been causing me a lot of issues as you can imagine.

I must mention that I am in fact a real person, I am not a malicious bot or individual, nor do I have the intention or facilities for that such thing, and I am 100% capable of proving I am in fact a human being.

Please consider updating your name list by removing the name murika_ and announce to your audience that mistakes have been made and that they will need to update their ban/block list or blacklist. 

Thank you very much.

**Comment by bastisawesome** [comment]
Updated NamelistMASTER.txt. I would like to reiterate, as noted in the README, that I am not the original owner of this repo, I am hosting it here for historical reference. This is a (mostly) unmaintained repo, and I have no connection to the original maintainer of this repo.

**Comment by captunnmurika** [comment]
Hi, thank you for your time and response. May I ask if you know who the original curator of this repo even though you have no connection to them?

**Comment by bastisawesome** [comment]
The original owner of this repo was Hackbolt, however he took it down due to uncertainty on how it would be managed in the future. I keep this copy up strictly for historical purposes, so people who want the original lists and tools can still access them.

**Comment by captunnmurika** [comment]
Thank you.
