### ISSUE TITLE
Updated username for user previously flagged.

### ISSUE THREAD

**Issue by captunnmurika** [bastisawesome/twitchbotsnbigots#3]
Hi, not sure if you remember me, but I opened an Issue a few years ago about username **murika_** being falsely flagged. The username has since been removed from the list and added to false positives, but I've also changed my Twitch username to **captunnmurika**.

I would like to request to have **captunnmurika** added to false positives as well. I can prove that I am the same person if necessary. 

Thank you.

**Comment by bastisawesome** [comment]
I don't see that username in [NamelistMASTER.txt](https://github.com/bastisawesome/twitchbotsnbigots/blob/main/NamelistMASTER.txt). As far as I can tell, there is no false-positive here. Can you please give the line number on which it appears, if it does?

**Comment by captunnmurika** [comment]
You misunderstood. My previous username (murika_) has already been removed and added to the whitelist, I'm requesting for my NEW username (captunnmurika) to be added to whitelist as well in case other people still have me banned/blocked.

**Comment by bastisawesome** [comment]
There is no whitelist. Requests are for removing a username that was added to the banlist in error. The false positives text file is only updated when a name is removed from the file listed above. I checked the banlist for your new username and did not find it. As it is not in the list, there is nothing to update.

**Comment by captunnmurika** [comment]
Yes, I meant to say false positives, my mistake. Since I actually changed my username rather close to the time of this previous issue I made in 2021 https://github.com/bastisawesome/twitchbotsnbigots/issues/2 do you have any suggestions on how to better damage control it since my new username isn't on false positives and the old username won't help in the unbanning process? I'm still finding channels I am blocked from til this day, it's why I'm opening this issue after all this time.

**Comment by bastisawesome** [comment]
Ah, I understand the issue now. I can go ahead and update the false positives to include the new username, but I'm not sure how many people use this updated list. For damage control, I'm afraid I can't offer much else to help.

**Comment by captunnmurika** [comment]
I understand, I'd appreciate it if you could update my new username to false positives, that will at least give me a better peace of mind. Thank you for your time!
